// Code generated by Slice Machine. DO NOT EDIT.

import Button from './Button';
import ButtonRow from './ButtonRow';
import Carousell from './Carousell';
import Clickwords from './Clickwords';
import Custumers from './Custumers';
import Footer from './Footer';
import Header from './Header';
import Imagerow from './Imagerow';
import Infobox from './Infobox';
import LoginFacebookGithub from './LoginFacebookGithub';
import LoginGoogle from './LoginGoogle';
import LogoButton from './LogoButton';
import NavigationItem from './NavigationItem';
import PageInfo from './PageInfo';
import Priceplan from './Priceplan';
import Quicknote from './Quicknote';
import TextPile from './TextPile';
import Textimage from './Textimage';
import Therms from './Therms';
import Welcom from './Welcom';
import WelcomeCarousel from './WelcomeCarousel';

export {
	Button,
	ButtonRow,
	Carousell,
	Clickwords,
	Custumers,
	Footer,
	Header,
	Imagerow,
	Infobox,
	LoginFacebookGithub,
	LoginGoogle,
	LogoButton,
	NavigationItem,
	PageInfo,
	Priceplan,
	Quicknote,
	TextPile,
	Textimage,
	Therms,
	Welcom,
	WelcomeCarousel,
};

export const components = {
	button: Button,
	button_row: ButtonRow,
	carousell: Carousell,
	clickwords: Clickwords,
	custumers: Custumers,
	footer: Footer,
	header: Header,
	imgrow: Imagerow,
	infobox: Infobox,
	log_face: LoginFacebookGithub,
	log_goog: LoginGoogle,
	logo_button: LogoButton,
	navigation_item: NavigationItem,
	slice1: PageInfo,
	priceplan: Priceplan,
	quicknote: Quicknote,
	text_pile: TextPile,
	textimg: Textimage,
	therms: Therms,
	welcom: Welcom,
	welcome_carousel: WelcomeCarousel,
};
