// Code generated by Slice Machine. DO NOT EDIT.

import Button from './Button';
import ButtonRow from './ButtonRow';
import Carousell from './Carousell';
import Custumers from './Custumers';
import Header from './Header';
import Imgrow from './Imgrow';
import Infobox from './Infobox';
import LogFaceGit from './LogFaceGit';
import LogGoog from './LogGoog';
import NavigationItem from './NavigationItem';
import PageInfo from './PageInfo';
import Textimg from './Textimg';
import TextPile from './TextPile';

export {
	Button,
	ButtonRow,
	Carousell,
	Custumers,
	Header,
	Imgrow,
	Infobox,
	LogFaceGit,
	LogGoog,
	NavigationItem,
	PageInfo,
	Textimg,
	TextPile,
};

export const components = {
	button: Button,
	button_row: ButtonRow,
	carousell: Carousell,
	custumers: Custumers,
	header: Header,
	imgrow: Imgrow,
	infobox: Infobox,
	log_face: LogFaceGit,
	log_goog: LogGoog,
	navigation_item: NavigationItem,
	slice1: PageInfo,
	textimg: Textimg,
	text_pile: TextPile,
};
