// Code generated by Slice Machine. DO NOT EDIT.

import Button from './Button';
import Header from './Header';
import Infobox from './Infobox';
import NavigationItem from './NavigationItem';
import PageInfo from './PageInfo';

export {
	Button,
	Header,
	Infobox,
	NavigationItem,
	PageInfo,
};

export const components = {
	button: Button,
	header: Header,
	infobox: Infobox,
	navigation_item: NavigationItem,
	slice1: PageInfo,
};
